# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!

tasks:
  default:
    cmds:
      - echo "{{.GREETING}}"
    silent: true
  build:
    cmds:
      - mkdir -p dist
      - go build -o dist/warp main.go
  release:
    cmds:
      - mkdir -p dist 
      - go build -o dist/warp -ldflags="-s -w" main.go
  run:
    cmds:
      - go run main.go